export interface LabelingInterfaceProps {
  currentTime: number;
  duration: number;
  isPlaying: boolean;
  zoomLevel: number;
  selectedSession: {
    id: string;
    name: string;
    date: string;
    duration: string;
    fileTypes: string[];
  };
  selectedCategory: any;
  quickTags: any[];
  selectedChannels: string[];
  searchTerm: string;
  isAddCategoryModalOpen: boolean;
  newCategoryName: string;
  isTimelineLocked: boolean;
  isChannelViewExpanded: boolean;
  allChannels: string[];
  isDeleteMode: boolean;
  categories: any[];
  selectedQuickTag: any;
  isQuickLabelDeleteMode: boolean;
  isStepDeleteMode: boolean;
  isStepTypeCardCollapsed: boolean;
  newStepName: string;
  isAddingStep: boolean;
  isAddingCategory: boolean;
  timeDisplayMode: string;
  isFlagSelected: boolean;
  onPlayPause: () => void;
  onSeek: (time: number) => void;
  onZoom: (direction: 'in' | 'out') => void;
  onAddQuickTag: () => void;
  onDeleteStep: () => void;
  onAddCategory: () => void;
  onDeleteQuickTag: () => void;
  onQuickTagSelect: () => void;
  onChannelSelect: (channel: string) => void;
  onChannelViewToggle: () => void;
  onTimeDisplayModeToggle: (mode: string) => void;
  onFlagToggle: () => void;
  formatTimecode: (time: number) => string;
  onStepTypeCardCollapse: () => void;
  onTimelineLockToggle: () => void;
  onSessionSelect: (sessionId: string) => void;
  onSearchClear: () => void;
  onAddCategoryClick: () => void;
  onAddCategoryCancel: () => void;
  onNewCategoryNameChange: (name: string) => void;
  onStepDeleteModeToggle: () => void;
  onCategorySelect: (categoryId: string) => void;
  onAddStepClick: () => void;
  onNewStepNameChange: (name: string) => void;
  onAddStepCancel: () => void;
  onSearchChange: (term: string) => void;
  sessions: any[];
  videoRef: React.RefObject<HTMLVideoElement>;
  canvasRef: React.RefObject<HTMLCanvasElement>;
  timelineRef: React.RefObject<HTMLDivElement>;
  onQuickLabelDeleteModeToggle: () => void;
  onDeleteCategory: () => void;
  onAddStep: () => void;
  timelineRows: any[];
  onRowReorder: (fromIndex: number, toIndex: number) => void;
  handleDeleteCategory: (categoryId: string) => void;
  handleDeleteStep: (step: string) => void;
  handleDeleteQuickTag: (tag: string) => void;
  filteredCategories: Array<{
    id: string;
    name: string;
    steps: string[];
  }>;
  handleSearchChange: (term: string) => void;
  handleSearchClear: () => void;
} 